FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Tambahkan baris build ini!
RUN npm run build

EXPOSE 3000