FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /usr/src/app

# Copy package dulu biar cache layer efisien
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy sisa file termasuk folder prisma
COPY . .

# Generate client saat build
RUN npx prisma generate --schema ./prisma/schema.prisma

EXPOSE 3000