FROM node:20-alpine
# Install library untuk keamanan Prisma & Postgres
RUN apk add --no-cache openssl
WORKDIR /usr/src/app

# 1. Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# 2. Copy kodingan lo
COPY . .

# 3. Generate Prisma Client (PENTING)
RUN npx prisma generate --schema ./prisma/schema.prisma

# 4. BUILD kodingan NestJS lo (Ini yang bikin folder /dist muncul)
RUN npm run build

EXPOSE 3000
# Biarkan command dihandle oleh docker-compose (start:prod)