FROM node:16.20.2

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Expose ports
EXPOSE 3000 5555

USER root
RUN chown -R node:node /usr/src/app/node_modules
USER node

# Start backend
CMD ["npm", "run", "start:dev"]
